# Generated by Django 3.1.3 on 2020-12-19 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Account', '0002_auto_20201218_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
