# Generated by Django 3.1.3 on 2020-12-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Checkout', '0002_auto_20201129_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='description',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('OnShipping', 'OnShipping'), ('Completed', 'Completed'),
                                            ('Canceled', 'Canceled')], default='New', max_length=200, null=True),
        ),
    ]
