# Generated by Django 3.1.3 on 2020-12-13 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Checkout', '0003_auto_20201213_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shippedDate',
        ),
    ]
