# Generated by Django 3.1.3 on 2020-12-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Checkout', '0008_order_date_ship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_finnish',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ship',
            field=models.DateTimeField(blank=True),
        ),
    ]
