# Generated by Django 3.1.3 on 2020-12-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0011_auto_20201221_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
