# Generated by Django 3.1.3 on 2020-11-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='demand',
            field=models.CharField(
                choices=[('Học tập - Văn phòng', 'Học tập - Văn phòng'), ('Đồ họa- Kĩ thuật', 'Đồ họa- Kĩ thuật'),
                         ('Gaming', 'Gaming'), ('Cao cấp-Sang trọng', 'Cao cấp-Sang trọng')], max_length=200,
                null=True),
        ),
    ]
