# Generated by Django 3.1.3 on 2020-11-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Shop', '0002_product_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Card',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='RAM',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Screen',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hard_disk',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
