# Generated by Django 3.1.3 on 2020-12-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Account', '0001_initial'),
        ('Shop', '0003_auto_20201129_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='dateAdded',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart_product',
            name='customer',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='Account.customer'),
        ),
        migrations.AddField(
            model_name='cart_product',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.cart'),
        ),
        migrations.AddField(
            model_name='cart_product',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
