# Generated by Django 3.1.3 on 2020-12-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Shop', '0004_auto_20201205_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
