# Generated by Django 3.1.3 on 2020-12-12 02:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Shop', '0006_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
